//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int id { get; set; }
        public string cliente { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string cuit { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string dni { get; set; }
        public string telefonoc { get; set; }
        public string celularc { get; set; }
        public string emailc { get; set; }
    }
}
