//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class metalEntities : DbContext
    {
        public metalEntities()
            : base("name=metalEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<archivos> archivos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<tamanio> tamanio { get; set; }
        public virtual DbSet<terminacion> terminacion { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<trabajosArchivos> trabajosArchivos { get; set; }
        public virtual DbSet<ordentrabajo> ordentrabajo { get; set; }
    }
}
