//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordentrabajo
    {
        public int id { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<System.DateTime> fechaRecepcion { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string trabajo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idTamanio { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> idTerminacion { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> enCurso { get; set; }
        public Nullable<bool> pausado { get; set; }
        public Nullable<bool> finalizado { get; set; }
        public Nullable<bool> entregado { get; set; }
        public Nullable<bool> cancelado { get; set; }
        public Nullable<int> idPago { get; set; }
        public Nullable<decimal> monto { get; set; }
    }
}
