//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajosArchivos
    {
        public System.Guid id { get; set; }
        public Nullable<int> idTrabajos { get; set; }
        public Nullable<int> idArchivos { get; set; }
    
        public virtual archivos archivos { get; set; }
    }
}
