//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public archivos()
        {
            this.trabajosArchivos = new HashSet<trabajosArchivos>();
        }
    
        public int id { get; set; }
        public string nombreReal { get; set; }
        public string nombreFisico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajosArchivos> trabajosArchivos { get; set; }
    }
}
